# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  SCHEME: Taksi
  TEST_DEVICE: platform=iOS Simulator,name=iPhone 11,OS=15.2

jobs:
  build:
    runs-on: macos-13
    timeout-minutes: 30

    steps:
    - name: Checkout project repo
      uses: actions/checkout@v3
      
    - name: Select Xcode
      run: sudo xcode-select -s "/Applications/Xcode_14.3.app"

    - name: Build
      shell: bash
      run: xcodebuild test -scheme '${{ env.SCHEME }}' -sdk iphonesimulator -destination '${{ env.TEST_DEVICE }}' -testPlan "Taksi" clean
