# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  SCHEME: Taksi
  TEST_DEVICE: platform=iOS Simulator,name=iPhone 11,OS=15.2

jobs:
  build:
    runs-on: macos-13.3
    timeout-minutes: 30

    steps:
    - name: Checkout project repo
      uses: actions/checkout@v3
    - name: Select Xcode
      run: sudo xcode-select -s "/Applications/Xcode_14.3.1.app"
    - name: Generate xcodeproj
      run: swift package generate-xcodeproj
    - name: Test
      shell: bash
      run: xcodebuild test -scheme "Taksi" -sdk iphoneos -destination "platform=iOS Simulator,name=iPhone 13,OS=15" clean
